### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by 021-projects** [kielabokkie/bitcoin-address-validator#1]
Hello! 

Please update package to PHP 8 compatibility (at least in composer.json) 

Thank you :)

**Comment by kielabokkie** [comment]
@BINGOSHARK I've just released v2.0.0 that adds support for PHP 8

A donation is highly appreciated to keep this package going. You can donate either via Github sponsors or sending some Bitcoin to `32vtWJSomccxQ6y1tgSwSHXN5PChpdYy27`, thanks! :)
