### ISSUE TITLE
support for taproot adresses

### ISSUE THREAD

**Issue by pkristian** [kielabokkie/bitcoin-address-validator#4]
since last BTC update including Taproot,
there is new type of addresses, i believe Bech version 1. for example:
`bc1pveaamy78cq5hvl74zmfw52fxyjun3lh7lgt44j03ygx02zyk8lesgk06f6`
problem is these addresses does not pass validation

**Comment by kielabokkie** [comment]
Thanks for reporting @pkristian. I'll have to see how to validate Taproot addresses.

**Comment by abgit** [comment]
hi, any news on this?

**Comment by kielabokkie** [comment]
@abgit I had a look into this and there is quite a lot involved into supporting taproot addresses. It's definitely on my radar but might take a while.

Would welcome a PR if anyone needs taproot support sooner than I can do it.

**Comment by kielabokkie** [comment]
So I started to make some progress on this. Need to find a bunch of good example addresses to test with but looks promising so far.

**Comment by abgit** [comment]
not sure if helps but here goes some valid taproot addresses:

```
bc1pxmxh0fz0cxrc8ryg2vh8egjj48wuwcme5zvv65q6rf5pgw7p2wmq73ax9h
bc1pr86eqm8tst0y4hlr3alxhstjzzlyyutz0qh908gegspcfe02fn0qqw4v8s
bc1pt0amqlkufexgyzvfzny76zjx6uf9hfv2t4rkk3dn32ttgsuxuh4qs25rz3
bc1pfpdsjumdvgz4ez7mke6p9c5x5gevqmk6yghcq6xkhly93wfwywvqnzvtqa
bc1p0nqm772qnsa507vz00ah48m0s0za6x2wegthcpejegkpla97tvfq84p0ec
bc1pssyggg2zkjluswj3r23cpna3vpcwh728pzd6a7ce7prqzq7qvtmsnd6qeg
bc1prvyu9ct508rhh3uxrzhqqj0jj82a5m86v2h065n2qhzlkfzlmmss4l2p0n
bc1pslrjuhu95t3dmewa6e3nmx2w5v42cv3pjpehll82hra5c5qss2eq3allfu
bc1pkyjcknnngxdd2wq5vq05xy3c7gmttgqlnk4078sahaletxreemssxxr8ss
bc1p5v6vn2wk5ljusa6e6jxzugc30svgvltkzexzwc4cj0uxgyyv98ys6lx0cc
bc1p6l3yhurkau5j8r9tv2uuyvteuwrkwkvhye9fs5qt2qld62vvyphs7s5yjv
bc1pdnkhtea4ynxq59rn2uvdpcxv2gsvhc8llhlylu5l0qyjn97nkgaqalcnfk
```

**Comment by kielabokkie** [comment]
Thanks @abgit, I'll add those to my test set. The test data on the actual `bitcoin/bitcoin` repo were a lot easier to copy over before, it's a bit of a mess now and much harder to find the edge cases. Can hopefully wrap it up and release somewhere next week.

**Comment by kielabokkie** [comment]
@abgit Do you happen to have a couple of testnet taproot addresses too? They are the ones that start with `tb1p`, I could only find one but would be good to have 3 or 4 extra random address to add to the tests.

**Comment by abgit** [comment]
@kielabokkie found some on testnet:

```
tb1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqp3mvzv
tb1pt4shxpethf5ft3d7edd0l7mugl6c6g6wz55llsyud0lj8qem8p4qfzxsrh
tb1phsephx8ymyeftf9ws95j8uhdzatyasv2q7tjq44t0ze6dmzdn23qezjzgx
tb1pe3fve082v0udkhnpad2h58cq5en3g9nsymy5hueqlnfzctzsax4qsjt8cm
tb1psxgpgtjmp5u9du20jtmhemsv729jzklckypnnuxq9ce9ewlktansjq87z0
```

**Comment by kielabokkie** [comment]
@pkristian @abgit I just tagged v2.1.0 that now has support for taproot address validation

**Comment by pkristian** [comment]
@pkristian will test after christmas, but thank you so much :))

**Comment by abgit** [comment]
Seems fixed. Good job. Thanks.

**Comment by pkristian** [comment]
@kielabokkie just tested.. works like a charm, thank you <3
